# The key to create CSRF tokens.
csrf_key: averysecretkey

# The path to GoogleApplicationCredentials file.
google_application_credentials: secrets/client_secret_1055532975349-enqf7slh6laaadbgc4fen95a3m554stu.apps.googleusercontent.com.json
# The path to the admin token file.
google_admin_token: secrets/google_admin_token.json

# The folder to put the log files in. The trailing slash is optional.
log_folder: logs
# The lowest level of logging to be placed in the log files.
# All logs are sent to STDOUT regardless of this setting.
# Acceptable values according to priority are: ERROR, WARNING, INFO, DEBUG
# Default is ERROR.
log_level: INFO

# The interface and port that the server will run on.
interface: 0.0.0.0
port: 8080

# Session configuration parameters
session_auth_key: prefertouseenvironmentvariable
session_duration: 60 # in minutes
session_enc_key:
session_secure: false
